name: Java CI with Maven - Test and package
on:
  pull_request:
    branches:
      - main
jobs:
  JavaCI:
    name: JavaCI
    runs-on: ubuntu-latest
    steps:
      - name: Chekout in repository
        uses: actions/checkout@v4
      - name: Cache mvn
        uses: actions/cache@v4
      - name: Java Initialize
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'
      - name: Maven run
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-')