name: Java CI with Maven - Test and package
on:
  pull_request:
    branches:
      - main
jobs:
  JavaCI:
    name: JavaCI
    runs-on: ubuntu-latest
    steps:
      - name: Chekout in repository
        uses: actions/checkout@v4
      - name: Java Initialize
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Maven run
        run: mvn -B package